from typing import Dict, Any

PROVENANCE_CATEGORIES = {
    "REAL_OBSERVED": "Direct sensor/camera/UAV measurements from live field deployment.",
    "REAL_IMPORTED": "Imported from verified public dataset or open data portal.",
    "DERIVED_FROM_REAL_DATA": "Calculated or aggregated directly from real observations.",
    "SIMULATED": "Generated by traffic microsimulation engine.",
    "SYNTHETIC": "Engineered baseline condition for stress testing.",
    "UNKNOWN": "Source provenance unverified."
}

class ProvenanceTracker:
    @staticmethod
    def create_metadata(
        source_name: str,
        source_url: str,
        dataset_name: str,
        download_date: str,
        license: str,
        coverage_area: str,
        time_period: str,
        field_description: str,
        data_type: str,
        processing_steps: str,
        classification: str = "REAL_IMPORTED"
    ) -> Dict[str, Any]:
        return {
            "source_name": source_name,
            "source_url": source_url,
            "dataset_name": dataset_name,
            "download_date": download_date,
            "license": license,
            "coverage_area": coverage_area,
            "time_period": time_period,
            "field_description": field_description,
            "data_type": data_type,
            "processing_steps": processing_steps,
            "classification": classification,
            "classification_description": PROVENANCE_CATEGORIES.get(classification, "Unknown")
        }
